// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4x4RqwkO1HAGfi-1VvLUQkDOJdkFeak',
    appId: '1:317799574631:android:af093e2e1d02114c0cb8c2',
    messagingSenderId: '317799574631',
    projectId: 'schoolerp-c855c',
    storageBucket: 'schoolerp-c855c.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9eJqpSTD4vsh8hvWE-y1mf1lR1TTdPjA',
    appId: '1:317799574631:web:8d181a3db766ff440cb8c2',
    messagingSenderId: '317799574631',
    projectId: 'schoolerp-c855c',
    authDomain: 'schoolerp-c855c.firebaseapp.com',
    storageBucket: 'schoolerp-c855c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPXZFzxkZAD6mXsQx3fMg4PQfq35mVQxc',
    appId: '1:317799574631:ios:efa46083dcab1db10cb8c2',
    messagingSenderId: '317799574631',
    projectId: 'schoolerp-c855c',
    storageBucket: 'schoolerp-c855c.appspot.com',
    iosBundleId: 'com.example.schoolerp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPXZFzxkZAD6mXsQx3fMg4PQfq35mVQxc',
    appId: '1:317799574631:ios:efa46083dcab1db10cb8c2',
    messagingSenderId: '317799574631',
    projectId: 'schoolerp-c855c',
    storageBucket: 'schoolerp-c855c.appspot.com',
    iosBundleId: 'com.example.schoolerp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9eJqpSTD4vsh8hvWE-y1mf1lR1TTdPjA',
    appId: '1:317799574631:web:8d7d234df1c94b5b0cb8c2',
    messagingSenderId: '317799574631',
    projectId: 'schoolerp-c855c',
    authDomain: 'schoolerp-c855c.firebaseapp.com',
    storageBucket: 'schoolerp-c855c.appspot.com',
  );

}